from tkinter import *
root=Tk()
Button(text="   ").grid(row=0,column=2)
Button(text="Понедельник:").grid(row=1,column=1)
Button(text="Вторник:").grid(row=2,column=1)
Button(text="Среда:").grid(row=3,column=1)
Button(text="Четверг:").grid(row=4,column=1)
Button(text="Пятница:").grid(row=5,column=1)
Button(text="Суббота:").grid(row=6,column=1)
Button(text="Воскресенье:").grid(row=7,column=1)
root.mainloop()